export const TEMPLATE_CATEGORIES = [
    'Social Media',
    'Instagram Post',
    'Instagram Story',
    'Flyer',
    'Poster',
    'Business Card',
    'Resume',
    'Presentation',
    'Thumbnails',
    'UI Blocks',
    'Marketing',
    'Ecommerce',
    'Brand Kits',
    'General',
];
