export const aiModeConfig = {
  image: {
    name: "Image Generation",
    showPrompt: true,
    showStyles: true,
    showModelSelector: true,
    showSizeSelector: true,
  },
  edit: {
    name: "Smart Edit",
    showPrompt: true,
    showBrushTools: true,
  },
  bg: {
    name: "Background Tools",
    showPrompt: false,
    showBGReplaceTools: true,
  },
  mockup: {
    name: "Mockup Generator",
    showPrompt: false,
    showMockupSelector: true,
    showMockupStyleSelector: true,
    showUploadDesign: true,
  },
  text: {
    name: "Text AI",
    showPrompt: true,
    showTextSettings: true,
  },
  template: {
    name: "Template Generator",
    showPrompt: true,
    showTemplateCategorySelector: true,
    showTemplateSizeSelector: true,
    showModelSelector: false,
  },
  audio: {
    name: "Audio AI",
    showPrompt: true,
    showVoiceSelector: true,
    showAudioUpload: true,
    showAudioTools: true,
    showModelSelector: true,
  },
  video: {
    name: "Video AI",
    showPrompt: true,
    showVideoUpload: true,
    showVideoSettings: true,
    showModelSelector: true,
    showDurationSelector: true,
    showMotionSelector: true,
  },
  assistant: {
    name: "Assistant",
    showPrompt: true,
  },
  dev: {
    name: "Dev Mode",
    showPrompt: false,
    showDevTools: true,
    isEditorMode: true,
  },
};
