export const templateCategoriesSeed = [
  // Global discovery
  { name: "Popular", slug: "popular", icon: "⭐" },
  { name: "Most Used", slug: "most-used", icon: "🔥" },
  { name: "Trending", slug: "trending", icon: "📈" },
  { name: "New Releases", slug: "new-releases", icon: "🆕" },
  { name: "Featured", slug: "featured", icon: "✨" },
  { name: "Premium", slug: "premium", icon: "💎" },
  { name: "Free Templates", slug: "free-templates", icon: "🆓" },
  { name: "AI Generated", slug: "ai-generated", icon: "🤖" },
  { name: "Recommended For You", slug: "recommended", icon: "👍" },
  { name: "Recently Published", slug: "recently-published", icon: "🕒" },
  { name: "Editor's Picks", slug: "editors-picks", icon: "🌟" },
  { name: "Top Rated", slug: "top-rated", icon: "🏅" },
  { name: "Fresh This Week", slug: "fresh-this-week", icon: "🗓️" },
  { name: "Top 100 Templates", slug: "top-100", icon: "💯" },
  { name: "Community Favorites", slug: "community-favorites", icon: "👥" },
  { name: "Seasonal Picks", slug: "seasonal-picks", icon: "🍁" },

  // Social media
  { name: "Instagram Posts", slug: "instagram-posts", icon: "📱" },
  { name: "Instagram Stories", slug: "instagram-stories", icon: "📲" },
  { name: "Instagram Reels", slug: "instagram-reels", icon: "🎞️" },
  { name: "Instagram Highlight Covers", slug: "instagram-highlight-covers", icon: "🏷️" },
  { name: "Facebook Posts", slug: "facebook-posts", icon: "📘" },
  { name: "Facebook Covers", slug: "facebook-covers", icon: "🖼️" },
  { name: "Facebook Ads", slug: "facebook-ads", icon: "📢" },
  { name: "Twitter Posts", slug: "twitter-posts", icon: "🐦" },
  { name: "LinkedIn Posts", slug: "linkedin-posts", icon: "💼" },
  { name: "LinkedIn Banners", slug: "linkedin-banners", icon: "🪧" },
  { name: "TikTok Posts", slug: "tiktok-posts", icon: "🎵" },
  { name: "TikTok Covers", slug: "tiktok-covers", icon: "🎶" },
  { name: "Pinterest Pins", slug: "pinterest-pins", icon: "📌" },
  { name: "Pinterest Story Pins", slug: "pinterest-story-pins", icon: "📍" },
  { name: "YouTube Thumbnails", slug: "youtube-thumbnails", icon: "🎬" },
  { name: "YouTube Channel Art", slug: "youtube-channel-art", icon: "📺" },
  { name: "YouTube End Screens", slug: "youtube-end-screens", icon: "🔚" },
  { name: "YouTube Video Chapters", slug: "youtube-chapters", icon: "⏩" },
  { name: "YouTube Shorts Covers", slug: "youtube-shorts", icon: "🎞️" },
  { name: "Twitch Banners", slug: "twitch-banners", icon: "🎮" },
  { name: "Twitch Offline Screens", slug: "twitch-offline-screens", icon: "📴" },
  { name: "Social Media Carousels", slug: "social-media-carousels", icon: "🖼️" },
  { name: "Social Ads Pack", slug: "social-ads-pack", icon: "🪧" },
  { name: "Influencer Media Kits", slug: "influencer-media-kits", icon: "📊" },
  { name: "Podcast Covers", slug: "podcast-covers", icon: "🎙️" },
  { name: "Blog Headers", slug: "blog-headers", icon: "📝" },
  { name: "Newsletter Graphics", slug: "newsletter-graphics", icon: "💌" },
  { name: "Medium Article Headers", slug: "medium-headers", icon: "✍️" },
  { name: "Social Quotes Templates", slug: "social-quotes", icon: "💬" },

  // Business & enterprise
  { name: "Business", slug: "business", icon: "💼" },
  { name: "Enterprise", slug: "enterprise", icon: "🏢" },
  { name: "Corporate", slug: "corporate", icon: "📊" },
  { name: "Company Profiles", slug: "company-profiles", icon: "🏙️" },
  { name: "Corporate Branding", slug: "corporate-branding", icon: "🎨" },
  { name: "Pitch Decks", slug: "pitch-decks", icon: "📈" },
  { name: "Sales Decks", slug: "sales-decks", icon: "💸" },
  { name: "Investor Decks", slug: "investor-decks", icon: "💰" },
  { name: "Startup Roadmaps", slug: "startup-roadmaps", icon: "🗺️" },
  { name: "Annual Reports", slug: "annual-reports", icon: "📘" },
  { name: "Quarterly Reports", slug: "quarterly-reports", icon: "📄" },
  { name: "Brand Guidelines", slug: "brand-guidelines", icon: "📚" },
  { name: "Business Plans", slug: "business-plans", icon: "📝" },
  { name: "Business Strategy Documents", slug: "business-strategy", icon: "📈" },
  { name: "Market Research", slug: "market-research", icon: "🔎" },
  { name: "Process Diagrams", slug: "process-diagrams", icon: "🔁" },
  { name: "Org Charts", slug: "org-charts", icon: "👤" },
  { name: "Project Management", slug: "project-management", icon: "📅" },
  { name: "Team Training", slug: "team-training", icon: "👥" },
  { name: "Case Studies", slug: "case-studies", icon: "📖" },
  { name: "Corporate Policies", slug: "corporate-policies", icon: "📜" },
  { name: "Contract Templates", slug: "contract-templates", icon: "✍️" },
  { name: "Business Cards", slug: "business-cards", icon: "💼" },
  { name: "Letterheads", slug: "letterheads", icon: "📄" },
  { name: "Invoices", slug: "invoices", icon: "🧾" },
  { name: "Receipts", slug: "receipts", icon: "🧾" },
  { name: "Purchase Orders", slug: "purchase-orders", icon: "🛒" },
  { name: "Service Agreements", slug: "service-agreements", icon: "📄" },
  { name: "NDAs", slug: "ndas", icon: "🤝" },
  { name: "Project Proposals", slug: "project-proposals", icon: "📃" },
  { name: "Company Brochures", slug: "company-brochures", icon: "📔" },
  { name: "Internal Reports", slug: "internal-reports", icon: "📑" },
  { name: "Business Presentations", slug: "business-presentations", icon: "🖥️" },
  { name: "Press Releases Templates", slug: "press-releases", icon: "📰" },
  { name: "Business Newsletter Templates", slug: "business-newsletters", icon: "🗞️" },
  { name: "Corporate Social Media Kits", slug: "corporate-social-kits", icon: "📱" },
  { name: "B2B Marketing Templates", slug: "b2b-marketing", icon: "📣" },
  { name: "CRM Templates", slug: "crm-templates", icon: "📇" },
  { name: "ERP Templates", slug: "erp-templates", icon: "🗂️" },

  // Marketing & sales
  { name: "Marketing Kits", slug: "marketing-kits", icon: "📣" },
  { name: "Sales Sheets", slug: "sales-sheets", icon: "📄" },
  { name: "Flyers", slug: "flyers", icon: "📰" },
  { name: "Posters", slug: "posters", icon: "📌" },
  { name: "Brochures", slug: "brochures", icon: "📔" },
  { name: "Event Promotions", slug: "event-promotions", icon: "🎟️" },
  { name: "Campaign Templates", slug: "campaign-templates", icon: "📢" },
  { name: "Seasonal Marketing Packs", slug: "seasonal-marketing", icon: "🍂" },
  { name: "Retail Sale Banners", slug: "retail-sale-banners", icon: "🛍️" },
  { name: "Launch Announcements", slug: "launch-announcements", icon: "🚀" },
  { name: "Brand Collateral Kits", slug: "brand-collateral-kits", icon: "🎨" },
  { name: "Press Media Kits", slug: "press-media-kits", icon: "📰" },
  { name: "Infographics", slug: "infographics", icon: "📈" },
  { name: "SEO Content Templates", slug: "seo-content", icon: "🔍" },
  { name: "Advertising Templates", slug: "advertising-templates", icon: "📢" },
  { name: "Billboard Designs", slug: "billboard-designs", icon: "🪧" },
  { name: "Email Headers", slug: "email-headers", icon: "✉️" },
  { name: "Email Marketing Templates", slug: "email-marketing", icon: "📧" },
  { name: "Digital Ads", slug: "digital-ads", icon: "💻" },
  { name: "Product Pitch Pages", slug: "product-pitch-pages", icon: "📄" },
  { name: "Case Study Templates", slug: "case-study-templates", icon: "📖" },
  { name: "Offer & Discount Graphics", slug: "offer-discount", icon: "🏷️" },
  { name: "Growth Marketing Templates", slug: "growth-marketing", icon: "📈" },
  { name: "Affiliate Kit Templates", slug: "affiliate-kits", icon: "🤝" },
  { name: "Product Explainer Templates", slug: "product-explainer", icon: "🧾" },

  // E-commerce & product
  { name: "Product Catalogs", slug: "product-catalogs", icon: "📦" },
  { name: "Product Sheets", slug: "product-sheets", icon: "📄" },
  { name: "Pricing Tables", slug: "pricing-tables", icon: "💲" },
  { name: "Ecommerce Banners", slug: "ecommerce-banners", icon: "🛒" },
  { name: "Product Launch Kits", slug: "product-launch-kits", icon: "🚀" },
  { name: "Coupons", slug: "coupons", icon: "🏷️" },
  { name: "Gift Vouchers", slug: "gift-vouchers", icon: "🎁" },
  { name: "Product Mockups", slug: "product-mockups", icon: "📸" },
  { name: "Wishlist Templates", slug: "wishlist-templates", icon: "🧾" },
  { name: "Amazon A+ Content", slug: "amazon-a-plus", icon: "🛒" },
  { name: "Etsy Templates", slug: "etsy-templates", icon: "🧶" },

  // Real estate
  { name: "Real Estate Flyers", slug: "real-estate-flyers", icon: "🏘️" },
  { name: "Property Listings", slug: "property-listings", icon: "🏠" },
  { name: "Open House", slug: "open-house", icon: "🚪" },
  { name: "Rental Listings", slug: "rental-listings", icon: "📄" },
  { name: "Architecture Portfolios", slug: "architecture-portfolios", icon: "📐" },
  { name: "Interior Lookbooks", slug: "interior-lookbooks", icon: "🛋️" },

  // Food & restaurant
  { name: "Restaurant Menus", slug: "restaurant-menus", icon: "🍽️" },
  { name: "Food Posters", slug: "food-posters", icon: "🍔" },
  { name: "Recipe Cards", slug: "recipe-cards", icon: "🍲" },
  { name: "Catering Templates", slug: "catering-templates", icon: "🥗" },

  // Education
  { name: "Class Notes", slug: "class-notes", icon: "📓" },
  { name: "Lesson Plans", slug: "lesson-plans", icon: "📘" },
  { name: "Worksheets", slug: "worksheets", icon: "📄" },
  { name: "Certificates", slug: "certificates", icon: "🏅" },
  { name: "Student Templates", slug: "student-templates", icon: "🎒" },
  { name: "Online Course Branding", slug: "online-course-branding", icon: "💻" },

  // Events & celebrations
  { name: "Wedding Invitations", slug: "wedding-invitations", icon: "💍" },
  { name: "Engagement Invitations", slug: "engagement-invitations", icon: "💍" },
  { name: "Birthday Invitations", slug: "birthday-invitations", icon: "🎂" },
  { name: "Anniversary Cards", slug: "anniversary-cards", icon: "🎉" },
  { name: "Baby Shower", slug: "baby-shower", icon: "🍼" },
  { name: "Gender Reveal", slug: "gender-reveal", icon: "🚼" },
  { name: "Retirement Cards", slug: "retirement-cards", icon: "🧓" },
  { name: "Funeral Programs", slug: "funeral-programs", icon: "🕊️" },
  { name: "Holiday Templates", slug: "holiday-templates", icon: "🎄" },
  { name: "Christmas", slug: "christmas", icon: "🎄" },
  { name: "New Year", slug: "new-year", icon: "🎆" },
  { name: "Halloween", slug: "halloween", icon: "🎃" },
  { name: "Thanksgiving", slug: "thanksgiving", icon: "🦃" },

  // Travel & tourism
  { name: "Travel Flyers", slug: "travel-flyers", icon: "✈️" },
  { name: "Destination Guides", slug: "destination-guides", icon: "🗺️" },
  { name: "Itineraries", slug: "itineraries", icon: "📅" },
  { name: "Hotel Brochures", slug: "hotel-brochures", icon: "🏨" },
  { name: "Tour Packages", slug: "tour-packages", icon: "🧳" },

  // Lifestyle & personal
  { name: "Fitness Templates", slug: "fitness-templates", icon: "💪" },
  { name: "Yoga Templates", slug: "yoga-templates", icon: "🧘" },
  { name: "Beauty Templates", slug: "beauty-templates", icon: "💄" },
  { name: "Photography Portfolios", slug: "photography-portfolios", icon: "📸" },
  { name: "Daily Planners", slug: "daily-planners", icon: "📅" },
  { name: "Budget Trackers", slug: "budget-trackers", icon: "💰" },
  { name: "Vision Boards", slug: "vision-boards", icon: "🧠" },

  // Health, medical & wellness
  { name: "Medical Posters", slug: "medical-posters", icon: "🏥" },
  { name: "Healthcare Flyers", slug: "healthcare-flyers", icon: "💉" },
  { name: "Public Health Notices", slug: "public-health-notices", icon: "📢" },
  { name: "Diet Plans", slug: "diet-plans", icon: "🥗" },
  { name: "Therapy Worksheets", slug: "therapy-worksheets", icon: "🧠" },

  // Tech, digital, UI/UX
  { name: "UI Kits", slug: "ui-kits", icon: "🖥️" },
  { name: "Wireframes", slug: "wireframes", icon: "📐" },
  { name: "App Mockups", slug: "app-mockups", icon: "📱" },
  { name: "Dashboard Templates", slug: "dashboard-templates", icon: "📊" },
  { name: "Landing Pages", slug: "landing-pages", icon: "🖥️" },
  { name: "User Flows", slug: "user-flows", icon: "🔀" },
  { name: "Persona Templates", slug: "persona-templates", icon: "🧑" },

  // Video, animation & streaming
  { name: "Video Thumbnails", slug: "video-thumbnails", icon: "🎬" },
  { name: "Video Title Cards", slug: "video-title-cards", icon: "🎞️" },
  { name: "Lower Thirds", slug: "lower-thirds", icon: "🔻" },
  { name: "Stream Overlays", slug: "stream-overlays", icon: "🎥" },
  { name: "Twitch Screens", slug: "twitch-screens", icon: "🖥️" },
  { name: "OBS Templates", slug: "obs-templates", icon: "🎛️" },
  { name: "Reels Templates", slug: "reels-templates", icon: "🎬" },
  { name: "TikTok Templates", slug: "tiktok-templates", icon: "🎶" },
  { name: "Storyboard Templates", slug: "storyboard-templates", icon: "📑" },
  { name: "Motion Graphic Frames", slug: "motion-graphic-frames", icon: "🎞️" },
  { name: "BRoll Title Cards", slug: "broll-title-cards", icon: "🎥" },
  { name: "Logo Animation Templates", slug: "logo-animation", icon: "✨" },
  { name: "Animated Social Posts", slug: "animated-social-posts", icon: "💫" },
  { name: "Video Intros", slug: "video-intros", icon: "🎬" },
  { name: "Video Outros", slug: "video-outros", icon: "⏭️" },

  // AI-powered
  { name: "AI Templates", slug: "ai-templates", icon: "✨" },
  { name: "AI Product Shots", slug: "ai-product-shots", icon: "📸" },
  { name: "AI Art Styles", slug: "ai-art-styles", icon: "🎨" },
  { name: "AI Mockups", slug: "ai-mockups", icon: "🧪" },
  { name: "AI Scenes", slug: "ai-scenes", icon: "🌌" },
];
